# Generated by Django 3.1.4 on 2023-04-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20230402_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organiser',
            new_name='is_organisor',
        ),
    ]
